specify public keys only
ory/oathkeeper pull request #695
Opened 2021-04-22 17:03 UTC by stensonb

the .well-known/jwks.json endpoint should (and does) only return the public keys of the JWKS (as described here: https://www.ory.sh/oathkeeper/docs/pipeline/mutator#configuration-1)

## Proposed changes

clarifying the data delivered at the .well-known/jwks.json endoint

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

2021-04-22 17:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/oathkeeper?pullRequest=695) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/oathkeeper?pullRequest=695) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/oathkeeper?pullRequest=695) it.</sub>

2021-04-23 07:00 UTC, aeneasr requested changes
Thank you!

Unfortunately as it says in the top of the file - this file is autogenerated and the source needs to be updated: https://github.com/ory/oathkeeper/blob/d942c043aa2370b87e0dd822440ad39d809755f9/api/credential.go#L48

2021-04-23 17:57 UTC, stensonb commented
yup, sure enough.  sorry, just getting the hang of the doc generator. :)

this does bring up a separate issue, however.  the generator indicates the `200` response is the entire `jsonWebKeySet`, which isn't accurate: https://github.com/ory/oathkeeper/blob/d942c043aa2370b87e0dd822440ad39d809755f9/api/credential.go#L56

the 200 response is actually a subset (only the public key details): https://github.com/ory/oathkeeper/blob/d942c043aa2370b87e0dd822440ad39d809755f9/api/credential.go#L70-L77

i'll create a private struct to hold the public key details and return that (and update the docs to reflect the private struct).  updated PR coming soon... :)

2021-04-25 17:46 UTC, aeneasr commented
> yup, sure enough. sorry, just getting the hang of the doc generator. :)

Don't worry - just thinking about how we can help contributors see this better as it's not the first time :) If you have any ideas please let me know!

> the 200 response is actually a subset (only the public key details):

So basically a different struct without the private key fields? I think that would be ok but is not really necessary in my opinion as noone is really parsing those fields themselves and they usually just pass them to some library. The fields are `omitempty` so basically not set usually! From my side no need to spend work on that :)

2021-05-02 15:52 UTC, aeneasr commented
Are you still up for the changes? :) If you need any help, let us know!

2021-05-11 09:09 UTC, aeneasr commented
Are you still up for the changes? :monocle_face: If you need any help, let us know!

I'll convert this to a draft in the meanwhile. When it's ready for review again, please remove the draft indicator! 👀

2021-09-18 15:24 UTC, closed without merging