feat: Ability to Configure Authorizers to "mutate" Headers into AuthenticationSession
ory/oathkeeper pull request #717
Opened 2021-05-04 22:02 UTC by wesleyfantinel

## Related issue

## Proposed changes

The remote authorizers may have useful context from user's permissions. So with this changes, custom authorizers using `remote` and `remote_json` can return some useful headers to be forward into the AuthenticationSession, meaning that these headers will be passed to upstream services. 

For example, an user containing scopes/branches inside an organization profile has some level of data addressed to him. In this case, the upstream service need to know that, and "filter" the data according to his "branch_id". The permission that is given to the user (and the remote authorizers manages) has a record of the "branch_id", for the following responses will be returned as status code 200 (if granted) and containing a header like `X-Branch-Id`. 

The upstream service receives the `X-Branch-Id` and does your thing.

---

Without this, we have to perform another request using the mutator `Hydrador` to retrieve the users' "branch_id", that is not a good performance approach in my vision for this set. 

## Checklist
- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](docs/docs).

## Further comments

2021-05-10 06:38 UTC, aeneasr requested changes
Thank you for the contribution! Unfortunately we can not accept contributions without tests. These are important to ensure that your feature does what it should, and it ensures that it keeps working even if others change your code!

if you need help with the tests feel free to ping a maintainer!

2021-05-10 12:58 UTC, wesleyfantinel commented
Ok, sending the tests.

2021-05-11 09:23 UTC, aeneasr commented
Looks like tests are failing for the new feature, could you take a look maybe? 🧐

2021-05-14 13:55 UTC, aeneasr approved these changes
This looks ready to be merged! The tests look great and the implementation too. I just would like to ask to rename the field to make it more obvious what it does :)

2021-05-14 13:55 UTC, aeneasr commented on docs/docs/pipeline/authz.md
>        }
Shouldn't this be an array?

```suggestion
      "allowed_remote_headers": [
        "X-Branch-Id"
      ]
```

2021-05-14 13:55 UTC, aeneasr commented on .schema/config.schema.json
> +        "allowed_remote_headers": {
I think this should have a different name to more clearly indicate what it is doing. What do you think about:

```suggestion
        "forward_response_headers_to_upstream": {
```

2021-05-14 13:55 UTC, aeneasr commented on .schema/config.schema.json
> +        "allowed_remote_headers": {
I think this should have a different name to more clearly indicate what it is doing. What do you think about:

```suggestion
        "forward_response_headers_to_upstream": {
```

2021-05-14 13:55 UTC, aeneasr commented on .schemas/authorizers.remote_json.schema.json
> +    "allowed_remote_headers": {
I think this should have a different name to more clearly indicate what it is doing. What do you think about:

```suggestion
        "forward_response_headers_to_upstream": {
```

2021-05-14 13:55 UTC, aeneasr commented on docs/docs/pipeline/authz.md
> +- `allowed_remote_headers` (slice of strings, optional) - The HTTP headers that
```suggestion
- `forward_response_headers_to_upstream` (slice of strings, optional) - The HTTP headers that 
```

2021-05-14 13:55 UTC, aeneasr commented on docs/docs/pipeline/authz.md
>      }
Should also be an array and renamed

2021-05-14 13:55 UTC, aeneasr commented on docs/docs/pipeline/authz.md
> +- `allowed_remote_headers` (slice of strings, optional) - The HTTP headers that
Should also be renamed

2021-05-14 13:55 UTC, aeneasr commented on internal/config/.oathkeeper.yaml
> +      allowed_remote_headers:
Don't forget to update this one :)

2021-05-14 13:55 UTC, aeneasr commented on internal/config/.oathkeeper.yaml
> +      allowed_remote_headers:
Don't forget to update this one :)

2021-05-14 13:55 UTC, aeneasr commented on pipeline/authz/remote.go
> +	AllowedRemoteHeaders []string          `json:"allowed_remote_headers"`
Don't forget to update this one :)

2021-05-14 13:55 UTC, aeneasr commented on pipeline/authz/remote_json.go
> +	AllowedRemoteHeaders []string `json:"allowed_remote_headers"`
Don't forget to update this one :)

2021-05-24 14:08 UTC, aeneasr approved these changes
Great job, thank you for your hard work!

2021-05-24 14:10 UTC, merged