feat: add request header in match context
ory/oathkeeper pull request #719
Opened 2021-05-05 09:09 UTC by msumit

## Related issue
https://github.com/ory/oathkeeper/issues/512

## Proposed changes
After wasting a lot of time on why I'm not able to use Headers within the Remote Authorizer, I found out that Oathkeeper isn't setting the Headers while initializing the AuthenticationSession. We use Remote Authorizer and pass on some key information through headers only & without this fix, we can't use Oathkeeper at all, so setting the request headers inside MatchContext. 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further comments
See this PR -> https://github.com/ory/oathkeeper/pull/718

2021-05-05 10:18 UTC, andriisoldatenko commented on proxy/request_handler_test.go
> -	return &http.Request{URL: x.ParseURLOrPanic(u), Method: "GET"}
```
return &http.Request{URL: x.ParseURLOrPanic(u), Method: "GET", Header: http.Header{"Test-Header":[]string{"Test-Value"}}}
```

2021-05-05 14:35 UTC, andriisoldatenko commented on proxy/request_handler_test.go
> +				Header:              newTestHeader(),
i think for expected results better to use constant / or literal instead of function

2021-05-06 05:41 UTC, msumit commented
@aeneasr can you plz review.

2021-05-10 06:19 UTC, aeneasr requested changes
Thank you this looks great and sorry for the late review - last week was hectic :)

Could you please also update the documentation in `docs/docs` on this? Thank you!

2021-05-11 09:23 UTC, aeneasr commented
Thank you, this looks great! The CI is failing because some files are formatted incorrectly. To format them, run:

```
$ make format
$ git commit -a -m "styles: format code"
$ git push
```

Thank you!

2021-05-11 16:10 UTC, aeneasr commented
Hmmm...why isn't the pipeline triggering -.-

2021-05-12 05:54 UTC, aeneasr commented
Yeah it's not your fault!

2021-05-12 05:55 UTC, aeneasr commented
But `ci/circleci: test` should be running and it's not :/ I have one guide regarding this:

---

Unfortunately, for some reason, the CircleCI tests are not running. Do you maybe follow your/a fork of this repository on CircleCI? If so, you need to unsubscribe / unwatch from that CircleCI project. Then, make another push to your branch using:

```
$ git commit --amend --allow-empty
$ git push --force
```

That should get the CI running! Thank you :)

2021-05-12 06:26 UTC, msumit commented
@aeneasr I think you need to approve something somewhere to kick off the tests. 
`First-time contributors need a maintainer to approve running workflows. Learn more.`

2021-05-14 05:42 UTC, msumit commented
@aeneasr can you look into this

2021-05-14 13:13 UTC, aeneasr commented
Hey there, sorry for the long delay - yesterday was a holiday :) I've approved the run. [I've also create a post on GH community](https://github.community/t/approve-run-is-a-major-pain-when-managing-large-oss-ecosystems/179765) regarding this as the current approval behavior is so annoying.

2021-05-14 13:31 UTC, aeneasr commented
Hm no, this looks like a circle ci issue. I'll run the tests locally

2021-05-14 13:32 UTC, aeneasr approved these changes

2021-05-14 13:32 UTC, merged

2021-05-14 13:32 UTC, aeneasr commented
Awesome, thank you! 🎉 Your contribution makes Ory better :)