feat: add Oathkeeper gRPC middleware
ory/oathkeeper pull request #994
Opened 2022-08-23 15:31 UTC by hperl

This PR adds a gRPC middleware to Oathkeeper to use in other services.

2022-08-25 15:39 UTC, zepatrik requested changes
Nice, the API looks good :+1: 
Just some small improvements I'd suggest.

2022-09-02 07:25 UTC, hperl commented on middleware/config.go
> +	viper.SetConfigFile(cfgFile)
Will be resolved by move to Koanf.

2022-09-02 08:46 UTC, hperl commented on middleware/grpc_middleware.go
> +var ErrDenied = status.Errorf(codes.Unauthenticated, "denied")
The problem is that this does not yet work for the version of herodot currently used in Oathkeeper. Will try again after the dependency bump.

Also, calling middlewares inside a middleware is not very clean, so I'd need to inline that functionality.

2022-09-06 13:12 UTC, hperl commented
Closed in favor of https://github.com/ory/oathkeeper/pull/1004

2022-09-06 13:12 UTC, closed without merging